import { Hackathon, Participant, Team, SatisfactionSurvey, FollowUp } from './types';

export const mockHackathons: Hackathon[] = [
  {
    id: 'hack-2025-001',
    name: 'AI 기반 사회문제 해결 해커톤 2025',
    university: '한국대학교',
    theme: 'AI 기반 사회문제 해결 솔루션 개발',
    startDate: '2025-03-13',
    endDate: '2025-03-15',
    venue: '한국대학교 공학관 B1 창업카페 및 강의실 301',
    host: 'SW중심대학사업단',
    organizer: '컴퓨터공학과 학생회',
    status: 'completed',
    description: '재학생의 문제해결 역량 강화와 팀 협업 경험 제공, SW·AI 분야 실무 적용 능력 향상을 목적으로 개최',
    maxTeams: 25,
    maxMembersPerTeam: 5,
    tracks: [
      { id: 't1', name: 'AI·데이터 활용', description: 'AI 모델 및 데이터 분석 기반 솔루션' },
      { id: 't2', name: '헬스케어·복지', description: '의료 및 사회복지 분야 기술 솔루션' },
      { id: 't3', name: '환경·지속가능성', description: '환경 보호 및 지속 가능한 발전 솔루션' },
      { id: 't4', name: '교육·사회', description: '교육 혁신 및 사회 문제 해결 솔루션' },
    ],
  },
  {
    id: 'hack-2025-002',
    name: '창업 아이디어 AI 해커톤 2025',
    university: '미래대학교',
    theme: 'AI를 활용한 창업 아이디어 프로토타이핑',
    startDate: '2025-11-10',
    endDate: '2025-11-11',
    venue: '미래대학교 창업지원센터',
    host: '창업지원단',
    organizer: '학생창업동아리연합',
    status: 'upcoming',
    description: '창업 아이디어를 AI 기술로 빠르게 프로토타이핑하고 검증하는 해커톤',
    maxTeams: 20,
    maxMembersPerTeam: 4,
    tracks: [
      { id: 't1', name: '핀테크·금융', description: '금융 서비스 혁신' },
      { id: 't2', name: '에듀테크', description: '교육 기술 솔루션' },
      { id: 't3', name: '헬스테크', description: '의료 기술 혁신' },
    ],
  },
];

export const mockParticipants: Participant[] = [
  {
    id: 'p001', hackathonId: 'hack-2025-001', name: '김민준', studentId: '2021001001',
    email: 'minjun@korea.ac.kr', major: '컴퓨터공학', majorCategory: '공학(컴퓨터·전자)',
    grade: 3, gender: '남성', isExternal: false, teamId: 'team-001',
    preScore: { understanding: 3, toolUsage: 2, problemSolving: 3, collaboration: 4, ethics: 3, completedAt: '2025-03-10' },
    postScore: { understanding: 5, toolUsage: 4, problemSolving: 5, collaboration: 5, ethics: 4, completedAt: '2025-03-15' },
    surveyCompleted: true, registeredAt: '2025-02-28',
  },
  {
    id: 'p002', hackathonId: 'hack-2025-001', name: '이서연', studentId: '2022002001',
    email: 'seoyeon@korea.ac.kr', major: '시각디자인', majorCategory: '예술·디자인',
    grade: 2, gender: '여성', isExternal: false, teamId: 'team-001',
    preScore: { understanding: 2, toolUsage: 2, problemSolving: 2, collaboration: 4, ethics: 3, completedAt: '2025-03-10' },
    postScore: { understanding: 4, toolUsage: 4, problemSolving: 4, collaboration: 5, ethics: 4, completedAt: '2025-03-15' },
    surveyCompleted: true, registeredAt: '2025-02-28',
  },
  {
    id: 'p003', hackathonId: 'hack-2025-001', name: '박지훈', studentId: '2022003001',
    email: 'jihoon@korea.ac.kr', major: '경영학', majorCategory: '인문·사회',
    grade: 2, gender: '남성', isExternal: false, teamId: 'team-001',
    preScore: { understanding: 2, toolUsage: 1, problemSolving: 3, collaboration: 4, ethics: 3, completedAt: '2025-03-10' },
    postScore: { understanding: 4, toolUsage: 3, problemSolving: 4, collaboration: 5, ethics: 4, completedAt: '2025-03-15' },
    surveyCompleted: false, registeredAt: '2025-03-01',
  },
  {
    id: 'p004', hackathonId: 'hack-2025-001', name: '최수아', studentId: '2021004001',
    email: 'suah@korea.ac.kr', major: '전자공학', majorCategory: '공학(컴퓨터·전자)',
    grade: 3, gender: '여성', isExternal: false, teamId: 'team-002',
    preScore: { understanding: 4, toolUsage: 3, problemSolving: 4, collaboration: 3, ethics: 4, completedAt: '2025-03-10' },
    postScore: { understanding: 5, toolUsage: 5, problemSolving: 5, collaboration: 4, ethics: 5, completedAt: '2025-03-15' },
    surveyCompleted: true, registeredAt: '2025-02-25',
  },
  {
    id: 'p005', hackathonId: 'hack-2025-001', name: '정태양', studentId: '2020005001',
    email: 'taeyang@korea.ac.kr', major: '소프트웨어학', majorCategory: '공학(컴퓨터·전자)',
    grade: 4, gender: '남성', isExternal: false, teamId: 'team-002',
    preScore: { understanding: 4, toolUsage: 4, problemSolving: 4, collaboration: 3, ethics: 3, completedAt: '2025-03-10' },
    postScore: { understanding: 5, toolUsage: 5, problemSolving: 5, collaboration: 4, ethics: 4, completedAt: '2025-03-15' },
    surveyCompleted: true, registeredAt: '2025-02-26',
  },
  {
    id: 'p006', hackathonId: 'hack-2025-001', name: '한나리', studentId: '2023006001',
    email: 'nari@korea.ac.kr', major: '심리학', majorCategory: '인문·사회',
    grade: 1, gender: '여성', isExternal: false, teamId: 'team-003',
    preScore: { understanding: 1, toolUsage: 1, problemSolving: 2, collaboration: 5, ethics: 4, completedAt: '2025-03-10' },
    postScore: { understanding: 3, toolUsage: 3, problemSolving: 3, collaboration: 5, ethics: 5, completedAt: '2025-03-15' },
    surveyCompleted: true, registeredAt: '2025-03-02',
  },
  {
    id: 'p007', hackathonId: 'hack-2025-001', name: '오현석', studentId: '2021007001',
    email: 'hyunseok@korea.ac.kr', major: '기계공학', majorCategory: '공학(기타)',
    grade: 3, gender: '남성', isExternal: false, teamId: 'team-003',
    preScore: { understanding: 3, toolUsage: 2, problemSolving: 4, collaboration: 3, ethics: 2, completedAt: '2025-03-10' },
    postScore: { understanding: 4, toolUsage: 4, problemSolving: 5, collaboration: 4, ethics: 4, completedAt: '2025-03-15' },
    surveyCompleted: true, registeredAt: '2025-03-01',
  },
  {
    id: 'p008', hackathonId: 'hack-2025-001', name: '윤채원', studentId: '2022008001',
    email: 'chaewon@other.ac.kr', major: '데이터사이언스', majorCategory: '공학(컴퓨터·전자)',
    grade: 2, gender: '여성', isExternal: true, teamId: 'team-004',
    preScore: { understanding: 3, toolUsage: 3, problemSolving: 3, collaboration: 4, ethics: 3, completedAt: '2025-03-10' },
    postScore: { understanding: 5, toolUsage: 5, problemSolving: 4, collaboration: 5, ethics: 4, completedAt: '2025-03-15' },
    surveyCompleted: true, registeredAt: '2025-03-03',
  },
  {
    id: 'p009', hackathonId: 'hack-2025-001', name: '임도현', studentId: '2023009001',
    email: 'dohyun@korea.ac.kr', major: '환경공학', majorCategory: '공학(기타)',
    grade: 1, gender: '남성', isExternal: false, teamId: 'team-004',
    preScore: { understanding: 2, toolUsage: 1, problemSolving: 2, collaboration: 3, ethics: 3, completedAt: '2025-03-10' },
    postScore: { understanding: 4, toolUsage: 3, problemSolving: 4, collaboration: 4, ethics: 4, completedAt: '2025-03-15' },
    surveyCompleted: false, registeredAt: '2025-03-04',
  },
  {
    id: 'p010', hackathonId: 'hack-2025-001', name: '강하늘', studentId: '2020010001',
    email: 'haneul@korea.ac.kr', major: '산업공학', majorCategory: '공학(기타)',
    grade: 4, gender: '여성', isExternal: false, teamId: 'team-005',
    preScore: { understanding: 4, toolUsage: 3, problemSolving: 4, collaboration: 4, ethics: 3, completedAt: '2025-03-10' },
    postScore: { understanding: 5, toolUsage: 4, problemSolving: 5, collaboration: 5, ethics: 4, completedAt: '2025-03-15' },
    surveyCompleted: true, registeredAt: '2025-02-27',
  },
  {
    id: 'p011', hackathonId: 'hack-2025-001', name: '신준호', studentId: '2021011001',
    email: 'junho@korea.ac.kr', major: '컴퓨터공학', majorCategory: '공학(컴퓨터·전자)',
    grade: 3, gender: '남성', isExternal: false, teamId: 'team-005',
    preScore: { understanding: 3, toolUsage: 3, problemSolving: 3, collaboration: 3, ethics: 3, completedAt: '2025-03-10' },
    postScore: { understanding: 4, toolUsage: 4, problemSolving: 4, collaboration: 4, ethics: 4, completedAt: '2025-03-15' },
    surveyCompleted: true, registeredAt: '2025-02-28',
  },
  {
    id: 'p012', hackathonId: 'hack-2025-001', name: '황미래', studentId: '2022012001',
    email: 'mirae@korea.ac.kr', major: '간호학', majorCategory: '기타',
    grade: 2, gender: '여성', isExternal: false, teamId: 'team-006',
    preScore: { understanding: 1, toolUsage: 1, problemSolving: 2, collaboration: 5, ethics: 5, completedAt: '2025-03-10' },
    postScore: { understanding: 3, toolUsage: 3, problemSolving: 3, collaboration: 5, ethics: 5, completedAt: '2025-03-15' },
    surveyCompleted: true, registeredAt: '2025-03-01',
  },
];

export const mockTeams: Team[] = [
  {
    id: 'team-001', hackathonId: 'hack-2025-001', name: '아이케어', trackId: 't2',
    members: ['p001', 'p002', 'p003'], leaderId: 'p001',
    project: {
      id: 'proj-001', teamId: 'team-001', name: 'EyeCare AI',
      description: '노인 안구 질환 조기 진단 AI 서비스',
      problemStatement: '농촌 지역 노인들의 안과 접근성 부족으로 실명 위험 증가',
      coreFeatures: '스마트폰 카메라로 망막 촬영 후 AI 진단, 가까운 안과 연결',
      techStack: ['Python', 'FastAPI', 'React', 'TensorFlow', 'OpenAI GPT-4'],
      githubUrl: 'https://github.com/example/eyecare-ai',
      submittedAt: '2025-03-15',
      completionLevel: '매우 우수',
      evaluationScore: {
        creativity: 22, techCompletion: 27, feasibility: 18, teamwork: 14, ux: 9,
        judgeComment: '아이디어의 독창성과 기술 완성도가 뛰어나며, 실제 사회 문제를 정확히 반영한 점이 우수함',
        award: '대상',
      },
    },
  },
  {
    id: 'team-002', hackathonId: 'hack-2025-001', name: '그린테크', trackId: 't3',
    members: ['p004', 'p005'], leaderId: 'p004',
    project: {
      id: 'proj-002', teamId: 'team-002', name: 'Carbon Tracker',
      description: '개인 탄소 발자국 실시간 측정 및 절감 가이드 앱',
      problemStatement: '개인의 탄소 배출량을 인식하기 어렵고 절감 방법을 모름',
      coreFeatures: '소비 패턴 분석으로 탄소 발자국 계산, AI 맞춤 절감 팁 제공',
      techStack: ['React Native', 'Node.js', 'MongoDB', 'Claude API'],
      githubUrl: 'https://github.com/example/carbon-tracker',
      submittedAt: '2025-03-15',
      completionLevel: '매우 우수',
      evaluationScore: {
        creativity: 21, techCompletion: 26, feasibility: 17, teamwork: 13, ux: 8,
        judgeComment: '환경 문제에 대한 실용적 접근법과 우수한 UX 설계가 돋보임',
        award: '최우수상',
      },
    },
  },
  {
    id: 'team-003', hackathonId: 'hack-2025-001', name: '에듀봇', trackId: 't4',
    members: ['p006', 'p007'], leaderId: 'p007',
    project: {
      id: 'proj-003', teamId: 'team-003', name: 'StudyMate AI',
      description: '학습 취약 학생을 위한 AI 1:1 튜터링 플랫폼',
      problemStatement: '사교육 접근성 격차로 학습 불평등 심화',
      coreFeatures: '개인 학습 패턴 분석, AI 맞춤 문제 출제, 취약점 자동 진단',
      techStack: ['Vue.js', 'Spring Boot', 'PostgreSQL', 'GPT API'],
      submittedAt: '2025-03-15',
      completionLevel: '우수',
      evaluationScore: {
        creativity: 20, techCompletion: 22, feasibility: 16, teamwork: 12, ux: 8,
        judgeComment: '교육 불평등 문제 해결에 대한 진지한 접근과 AI 활용이 인상적',
        award: '우수상',
      },
    },
  },
  {
    id: 'team-004', hackathonId: 'hack-2025-001', name: '세이프티넷', trackId: 't2',
    members: ['p008', 'p009'], leaderId: 'p008',
    project: {
      id: 'proj-004', teamId: 'team-004', name: 'SafetyNet',
      description: '1인 가구 노인 안전 모니터링 IoT+AI 플랫폼',
      problemStatement: '1인 노인 가구의 고독사·낙상 사고 증가',
      coreFeatures: '생활 패턴 이상 감지 AI, 보호자 실시간 알림, 119 자동 연계',
      techStack: ['Python', 'IoT', 'Firebase', 'React', 'TensorFlow Lite'],
      submittedAt: '2025-03-15',
      completionLevel: '우수',
      evaluationScore: {
        creativity: 19, techCompletion: 24, feasibility: 15, teamwork: 11, ux: 7,
        judgeComment: '사회적 필요성이 높은 주제 선택과 기술 구현력이 우수함',
        award: '우수상',
      },
    },
  },
  {
    id: 'team-005', hackathonId: 'hack-2025-001', name: 'AI마켓', trackId: 't1',
    members: ['p010', 'p011'], leaderId: 'p010',
    project: {
      id: 'proj-005', teamId: 'team-005', name: 'LocalMart AI',
      description: '전통시장 소상공인 AI 판매 최적화 플랫폼',
      problemStatement: '전통시장 소상공인의 디지털 전환 어려움',
      coreFeatures: '수요 예측 AI, 재고 최적화, SNS 마케팅 자동화',
      techStack: ['React', 'FastAPI', 'PostgreSQL', 'OpenAI API'],
      submittedAt: '2025-03-15',
      completionLevel: '양호',
      evaluationScore: {
        creativity: 18, techCompletion: 20, feasibility: 14, teamwork: 11, ux: 7,
        judgeComment: '현실적인 문제 정의와 비즈니스 관점의 접근이 좋으나 기술 완성도 보완 필요',
        award: '장려상',
      },
    },
  },
  {
    id: 'team-006', hackathonId: 'hack-2025-001', name: '케어링크', trackId: 't2',
    members: ['p012'], leaderId: 'p012',
    project: {
      id: 'proj-006', teamId: 'team-006', name: 'CareLink',
      description: '외국인 환자를 위한 AI 의료 통역 서비스',
      problemStatement: '언어 장벽으로 인한 외국인 환자 의료 서비스 접근성 문제',
      coreFeatures: '실시간 의료 통역 AI, 증상 설명 지원, 처방전 번역',
      techStack: ['Flutter', 'FastAPI', 'GPT-4', 'Whisper API'],
      submittedAt: '2025-03-15',
      completionLevel: '양호',
      evaluationScore: {
        creativity: 20, techCompletion: 18, feasibility: 14, teamwork: 10, ux: 8,
        judgeComment: '글로벌 관점의 의료 접근성 개선 아이디어가 창의적이며 잠재력 높음',
        award: '특별상',
      },
    },
  },
];

export const mockSurveys: SatisfactionSurvey[] = [
  {
    participantId: 'p001', hackathonId: 'hack-2025-001',
    overall: 5, theme: 5, mentoring: 4, venue: 3, fairness: 4, rewillingness: 5,
    positiveComment: '팀 빌딩 세션을 통해 다양한 전공의 학생과 교류할 수 있어 좋았습니다.',
    improvementComment: '야간 시간대 냉방이 조금 부족했습니다.',
    nps: 9, completedAt: '2025-03-16',
  },
  {
    participantId: 'p002', hackathonId: 'hack-2025-001',
    overall: 4, theme: 4, mentoring: 5, venue: 4, fairness: 4, rewillingness: 5,
    positiveComment: '멘토 세션이 실질적인 기술 방향 결정에 도움이 되었습니다.',
    improvementComment: '심사 기준을 사전에 더 자세히 공지해주었으면 합니다.',
    nps: 8, completedAt: '2025-03-16',
  },
  {
    participantId: 'p004', hackathonId: 'hack-2025-001',
    overall: 5, theme: 5, mentoring: 3, venue: 4, fairness: 5, rewillingness: 5,
    positiveComment: '36시간이라는 제한 시간이 몰입감을 높이는 데 효과적이었습니다.',
    improvementComment: '멘토 1인당 담당 팀이 너무 많아 대기 시간이 발생했습니다.',
    nps: 9, completedAt: '2025-03-17',
  },
  {
    participantId: 'p005', hackathonId: 'hack-2025-001',
    overall: 5, theme: 4, mentoring: 4, venue: 3, fairness: 4, rewillingness: 5,
    positiveComment: '심사 후 심사위원의 상세한 피드백이 성장에 큰 도움이 되었습니다.',
    improvementComment: '야간 식사 메뉴 다양성이 부족했습니다.',
    nps: 10, completedAt: '2025-03-17',
  },
  {
    participantId: 'p006', hackathonId: 'hack-2025-001',
    overall: 4, theme: 5, mentoring: 4, venue: 4, fairness: 4, rewillingness: 4,
    positiveComment: '처음 참가했는데 멘토분들이 친절하게 도와주셔서 좋았습니다.',
    improvementComment: '수상팀 후속 지원 프로그램이 있었으면 합니다.',
    nps: 8, completedAt: '2025-03-16',
  },
  {
    participantId: 'p007', hackathonId: 'hack-2025-001',
    overall: 4, theme: 4, mentoring: 3, venue: 4, fairness: 4, rewillingness: 5,
    positiveComment: '다전공 팀 구성이 새로운 시각을 제공해 주었습니다.',
    improvementComment: '멘토 예약제 도입이 필요합니다.',
    nps: 7, completedAt: '2025-03-17',
  },
  {
    participantId: 'p008', hackathonId: 'hack-2025-001',
    overall: 5, theme: 5, mentoring: 5, venue: 4, fairness: 5, rewillingness: 5,
    positiveComment: '타교 학생으로서도 편하게 참가할 수 있었습니다.',
    improvementComment: '온라인 참가 옵션도 검토해 주세요.',
    nps: 9, completedAt: '2025-03-16',
  },
  {
    participantId: 'p010', hackathonId: 'hack-2025-001',
    overall: 4, theme: 4, mentoring: 4, venue: 3, fairness: 4, rewillingness: 4,
    positiveComment: '실제 비즈니스 관점에서의 멘토링이 유익했습니다.',
    improvementComment: '좌석이 조금 협소했습니다.',
    nps: 8, completedAt: '2025-03-17',
  },
  {
    participantId: 'p011', hackathonId: 'hack-2025-001',
    overall: 4, theme: 4, mentoring: 4, venue: 4, fairness: 4, rewillingness: 4,
    positiveComment: '전반적으로 잘 운영된 행사였습니다.',
    improvementComment: '다음에는 더 많은 트랙이 있으면 좋겠습니다.',
    nps: 7, completedAt: '2025-03-16',
  },
  {
    participantId: 'p012', hackathonId: 'hack-2025-001',
    overall: 5, theme: 5, mentoring: 4, venue: 4, fairness: 5, rewillingness: 5,
    positiveComment: '의료 분야 멘토와의 대화가 매우 유익했습니다.',
    improvementComment: '의료 관련 트랙이 더 있으면 좋겠습니다.',
    nps: 10, completedAt: '2025-03-16',
  },
];

export const mockFollowUps: FollowUp[] = [
  {
    participantId: 'p001', hackathonId: 'hack-2025-001', period: '3개월',
    continuedDevelopment: true, startupConnected: true, patentFiled: false, externalAward: true,
    currentStatus: '교내 창업 동아리 연계하여 MVP 개발 중. 교내 창업 경진대회 장려상 수상',
    completedAt: '2025-06-15',
  },
  {
    participantId: 'p004', hackathonId: 'hack-2025-001', period: '3개월',
    continuedDevelopment: true, startupConnected: false, patentFiled: false, externalAward: false,
    currentStatus: '개인 GitHub에서 오픈소스로 공개, 스타 47개 획득',
    completedAt: '2025-06-15',
  },
  {
    participantId: 'p005', hackathonId: 'hack-2025-001', period: '3개월',
    continuedDevelopment: true, startupConnected: false, patentFiled: false, externalAward: false,
    currentStatus: '캡스톤 디자인 프로젝트로 연계하여 발전 중',
    completedAt: '2025-06-15',
  },
];

// ========== 진단 문항 ==========
export const diagnosisQuestions = [
  // AI 이해도
  {
    id: 'q1', category: 'understanding' as const, categoryLabel: 'AI 이해도',
    question: '머신러닝과 딥러닝의 차이점을 설명할 수 있나요?',
    options: ['전혀 모름', '들어본 적 있음', '개념 이해', '설명 가능', '타인에게 가르칠 수 있음'],
  },
  {
    id: 'q2', category: 'understanding' as const, categoryLabel: 'AI 이해도',
    question: 'AI 모델의 한계(환각, 편향 등)를 이해하고 있나요?',
    options: ['전혀 모름', '들어본 적 있음', '개념 이해', '사례 설명 가능', '비판적 분석 가능'],
  },
  // 도구 활용능력
  {
    id: 'q3', category: 'toolUsage' as const, categoryLabel: '도구 활용능력',
    question: 'ChatGPT, Claude 등 AI 도구를 업무/학습에 활용해본 경험은?',
    options: ['사용 안 함', '1-2회 사용', '가끔 사용', '자주 사용', '전문적으로 활용'],
  },
  {
    id: 'q4', category: 'toolUsage' as const, categoryLabel: '도구 활용능력',
    question: 'AI API를 활용하여 간단한 서비스를 개발할 수 있나요?',
    options: ['전혀 불가', '개념만 앎', '튜토리얼 따라 가능', '독립적으로 가능', '응용 개발 가능'],
  },
  // 문제 해결력
  {
    id: 'q5', category: 'problemSolving' as const, categoryLabel: '문제 해결력',
    question: '실제 문제에 AI를 적용할 수 있는 방법을 찾을 수 있나요?',
    options: ['전혀 불가', '아이디어 수준', '간단한 적용 가능', '구체적 설계 가능', '다양한 해결책 제시'],
  },
  {
    id: 'q6', category: 'problemSolving' as const, categoryLabel: '문제 해결력',
    question: 'AI 프로젝트에서 데이터 수집 및 전처리를 수행할 수 있나요?',
    options: ['전혀 모름', '개념만 앎', '기본 처리 가능', '다양한 처리 가능', '최적화까지 가능'],
  },
  // 협업/커뮤니케이션
  {
    id: 'q7', category: 'collaboration' as const, categoryLabel: '협업/커뮤니케이션',
    question: 'AI 프로젝트에서 비개발자와 소통하며 협업할 수 있나요?',
    options: ['매우 어려움', '어려움', '보통', '잘함', '매우 잘함'],
  },
  {
    id: 'q8', category: 'collaboration' as const, categoryLabel: '협업/커뮤니케이션',
    question: 'AI 기술을 비전문가에게 쉽게 설명할 수 있나요?',
    options: ['전혀 불가', '어려움', '기본 설명 가능', '명확히 설명 가능', '다양한 방식으로 전달'],
  },
  // 윤리적 판단력
  {
    id: 'q9', category: 'ethics' as const, categoryLabel: '윤리적 판단력',
    question: 'AI 시스템의 공정성과 편향 문제를 인식하고 있나요?',
    options: ['전혀 모름', '들어본 적 있음', '개념 이해', '사례 분석 가능', '해결책 제시 가능'],
  },
  {
    id: 'q10', category: 'ethics' as const, categoryLabel: '윤리적 판단력',
    question: 'AI 개인정보 보호 및 책임 있는 AI 사용 원칙을 알고 있나요?',
    options: ['전혀 모름', '막연히 앎', '기본 원칙 이해', '구체적 적용 가능', '정책 수준 이해'],
  },
];

// Benchmark data for university comparison
export const mockBenchmarkData = [
  {
    university: '서울대학교',
    participantCount: 98,
    avgPreScore: 3.2,
    avgPostScore: 4.3,
    growthRate: 34.4,
    satisfaction: 4.5,
    nps: 72,
    projectSubmitRate: 89,
  },
  {
    university: '연세대학교',
    participantCount: 85,
    avgPreScore: 3.0,
    avgPostScore: 4.1,
    growthRate: 36.7,
    satisfaction: 4.3,
    nps: 68,
    projectSubmitRate: 85,
  },
  {
    university: '고려대학교',
    participantCount: 92,
    avgPreScore: 3.1,
    avgPostScore: 4.2,
    growthRate: 35.5,
    satisfaction: 4.4,
    nps: 70,
    projectSubmitRate: 87,
  },
  {
    university: 'KAIST',
    participantCount: 76,
    avgPreScore: 3.8,
    avgPostScore: 4.6,
    growthRate: 21.1,
    satisfaction: 4.6,
    nps: 78,
    projectSubmitRate: 92,
  },
  {
    university: '성균관대학교',
    participantCount: 88,
    avgPreScore: 2.9,
    avgPostScore: 3.9,
    growthRate: 34.5,
    satisfaction: 4.2,
    nps: 65,
    projectSubmitRate: 82,
  },
  {
    university: '한양대학교',
    participantCount: 94,
    avgPreScore: 3.0,
    avgPostScore: 4.0,
    growthRate: 33.3,
    satisfaction: 4.3,
    nps: 67,
    projectSubmitRate: 84,
  },
  {
    university: '중앙대학교',
    participantCount: 72,
    avgPreScore: 2.8,
    avgPostScore: 3.7,
    growthRate: 32.1,
    satisfaction: 4.1,
    nps: 62,
    projectSubmitRate: 79,
  },
  {
    university: '경희대학교',
    participantCount: 68,
    avgPreScore: 2.7,
    avgPostScore: 3.6,
    growthRate: 33.3,
    satisfaction: 4.0,
    nps: 60,
    projectSubmitRate: 77,
  },
];
